apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  APP_JWT_SECRET: "dGhpc0lzQVZlcnlMb25nU2VjcmV0S2V5VGhhdElzQXRMZWFzdDI1NkJpdHNMb25n"
  APP_JWT_EXPIRATION: "86400000"
  APP_SERVICE_TIMEOUT: "5000"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE: "health,info,metrics,prometheus"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
