apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/order_db"
  SPRING_DATASOURCE_USERNAME: "demo_user"
  SPRING_DATASOURCE_PASSWORD: "demo_password"
