apiVersion: v1
kind: Service
metadata:
  name: hibernate-demo
spec:
  selector:
    app: hibernate-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
